dev:
  debug: false
  version: 2.3.0-alpha1
  maintainer:
    name: Exybore
    link: https://exybore.becauseofprog.fr
bot:
  name: Boîte à bois
  token: Bot's token
  id: 549219394513797130
  illustration: https://cdn.becauseofprog.fr/v2/projects/boite-a-bois.png
  website: https://github.com/BecauseOfProg/boite-a-bois
  prefix: b@
  color: 12000284
categories:
  default:
    name: Non classé
    emoji: x
  weather:
    name: Météo
    emoji: white_sun_rain_clouds
  games:
    name: Jeux
    emoji: video_game
  fun:
    name: Fun
    emoji: tada
  utilities:
    name: Utilitaires
    emoji: wrench
  teams:
    name: Équipes
    emoji: pushpin
assets:
  weather_api_key: The OpenWeatherMap API key
database:
  address: localhost
  port: 1234
  username: boite-a-bois
  password:
  auth_source: boite-a-bois
